### ISSUE TITLE
Typo - Pinterest is missing an E in the plugin.

### ISSUE THREAD

**Issue by easilyamused** [Shelob9/blockswp-share-block#24]
Pinterest is spelt wrong in the options. Missing an E.

I hate that word...

![screenshot 2018-01-04 15 33 59](https://user-images.githubusercontent.com/128621/34583410-a7ab8ece-f165-11e7-9987-87e3299a5ed6.png)

**Comment by Shelob9** [comment]
close via 
d5e1a2b
